version: 0.2

phases:
  install:
    commands:
      - npm install
      - cd client
      - npm install
      - npm run build
      - cd ..
      - mkdir -p dist/public
      - cp -r client/dist/* dist/public/
  build:
    commands:
      - npm run build
artifacts:
  files:
    - dist/**
    - package.json
    - package-lock.json
    - buildspec.yml
    - .ebextensions/** # if you have any 